spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 600000

  jpa:
    hibernate:
      ddl-auto: update
      type:
        preferred_uuid_jdbc_type: VARCHAR
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false

  servlet:
    multipart:
      max-file-size: "2GB"
      max-request-size: "2GB"

jwt:
  secret: ${TOKEN_SECRETKEY}

storage:
  dir: ${DIR}
  temp:
    path: ${TEMP}
