name: Build, Publish and Deploy Docker Image

on:
  push:
    branches: [ main, master ]
    paths:
      - '**/src/main/**'
      - 'Dockerfile'
      - 'build.gradle'
      - '../../core/docker-compose.prod.yml'

jobs:

  changes:
    runs-on: ubuntu-latest
    outputs:
      relevant: ${{ steps.filter.outputs.relevant }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            relevant:
              - 'core/src/main/**'
              - 'Dockerfile'
              - 'pom.xml'

  build-and-push:
    needs: changes
    if: needs.changes.outputs.relevant == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: ./core/
          file: ./core/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/eds3l:photodrive
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build-and-push
    if: always() && (needs.build-and-push.result == 'success' || needs.build-and-push.result == 'skipped')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Copy docker-compose to VPS
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "core/docker-compose.prod.yml"
          target: "/home/${{ secrets.USERNAME }}/photodrive"

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |
            echo "${{ secrets.DOCKER_TOKEN }}" | docker login docker.io -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            
            export DATASOURCE_PASSWORD="${{ secrets.DATASOURCE_PASSWORD }}"
            export DATASOURCE_URL="${{ secrets.DATASOURCE_URL }}"
            export DATASOURCE_USERNAME="${{ secrets.DATASOURCE_USERNAME }}"
            export MAIL_HOST="${{ secrets.MAIL_HOST }}"
            export MAIL_PASSWORD="${{ secrets.MAIL_PASSWORD }}"
            export MAIL_USERNAME="${{ secrets.MAIL_USERNAME }}"
            export DIR="${{ secrets.DIR }}"
            export TEMP="${{ secrets.TEMP }}"
            export TOKEN_SECRETKEY="${{ secrets.TOKEN_SECRETKEY }}"
            export ORG_MAX_SIZE="${{ secrets.ORG_MAX_SIZE }}"
            export SWAGGER_IP_ONE:"${{ secrets.SWAGGER_IP_ONE }}"
            export SWAGGER_IP_TWO:"${{ secrets.SWAGGER_IP_TWO }}"

            if [ -z "SWAGGER_IP_ONE" ]; then echo "BLAD: SWAGGER_IP_ONE jest puste!"; else echo "SWAGGER_IP_ONE ma wartosc"; fi


            cd /home/${{ secrets.USERNAME }}/photodrive
            docker pull docker.io/${{ secrets.DOCKER_USERNAME }}/eds3l:photodrive
            
            docker compose -f core/docker-compose.prod.yml up -d --remove-orphans